# helmi authentication
username: ""
password: ""

# domain returned in credentials
serviceEndpointDomain: ~

# ingress domain of helmi provisioned services
baseIngressDomain: ~

# map of helm repos to add during initialization, for example:
#  --set 'repositories.monostream=http://helm-charts.monocloud.io'
repositories: ~

# URL of the helmi catalog path or url (e.g. http://example.com/catalog.zip)
catalogUrl: ~

# tiller namespace
tillerNamespace: ~

# helm namespace
helmNamespace: ~

# Bind ports on the hostNetwork
hostNetwork: false

image:
  repository: monostream/helmi
  tag: "20190411.0"
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - helmi.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

kubeConfig: |
  ""

service:
  name: helmi
  type: ClusterIP
  nodePort: ""
  loadBalancerIP: ""

## If true, create & use RBAC resources
rbac:
  create: true

replicaCount: 2

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
  #  cpu: 100m
   memory: 512Mi
  requests:
  #  cpu: 100m
   memory: 256Mi

environment: {}

## Use password authentication
usePassword: true
