apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helmi.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "helmi.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "helmi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "helmi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.serviceEndpointDomain }}
          - name: DOMAIN
            value: {{ .Values.serviceEndpointDomain | quote }}
          {{- end }}
          {{- if .Values.baseIngressDomain }}
          - name: INGRESS_DOMAIN
            value: {{ .Values.baseIngressDomain | quote }}
          {{- end }}
          {{- if .Values.tillerNamespace }}
          - name: TILLER_NAMESPACE
            value: {{ .Values.tillerNamespace | quote }}
          {{- end }}
          {{- if .Values.helmNamespace }}
          - name: HELM_NAMESPACE
            value: {{ .Values.helmNamespace | quote }}
          {{- end }}
          - name: CATALOG_URL
            value: {{ required ".Values.catalogUrl is required!" .Values.catalogUrl | quote }}
          {{- if .Values.repositories }}
          - name: REPOSITORY_URLS
            value: {{ .Values.repositories | toJson | quote }}
          {{- end }}
          {{- if .Values.usePassword }}
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "helmi.name" . }}
                key: helmi-username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "helmi.name" . }}
                key: helmi-password
          {{- end }}
          {{- if .Values.environment }}
          {{- range $key, $value := .Values.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /liveness
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret | quote}}
      {{- end }}
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "helmi.name" . }}
      {{- end }}
