{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "helmi.name" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "helmi.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "helmi.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{ range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: http
    {{ end }}
{{- end -}}
