{{- if .Values.usePassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helmi.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "helmi.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.username }}
  helmi-username: {{ .Values.username | b64enc | quote }}
  {{- else }}
  helmi-username: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.password }}
  helmi-password: {{ .Values.password | b64enc | quote }}
  {{- else }}
  helmi-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}