apiVersion: v1
kind: Service
metadata:
  name: {{ template "helmi.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "helmi.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: 80
      targetPort: 5000
      protocol: TCP
    {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "helmi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}